name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: build32
      run: |
        mkdir build32
        cd build32
        cmake -G "Visual Studio 16 2019" -A Win32 ..
        cmake --build . --config Release
    - name: build64
      run: |
        mkdir build64
        cd build64
        cmake -G "Visual Studio 16 2019" -A x64 ..
        cmake --build . --config Release
